### ISSUE TITLE
could not execute buy: error placing order (Insufficient funds)

### ISSUE THREAD

**Issue by vitorego** [DeviaVir/zenbot#187]
Hi,
I got this error this morning:
```
`{ Error: non-200 status: 400
    at statusErr (/home/vitorego/download/zenbot/extensions/gdax/exchange.js:26:17)
    at /home/vitorego/download/zenbot/extensions/gdax/exchange.js:113:25
    at Request._callback (/home/vitorego/download/zenbot/node_modules/gdax/lib/clients/public.js:45:7)
    at Request.self.callback (/home/vitorego/download/zenbot/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/vitorego/download/zenbot/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/vitorego/download/zenbot/node_modules/request/request.js:965:12)
  code: 'HTTP_STATUS',
  body: { message: 'Insufficient funds' },
  desc: 'could not execute buy: error placing order' }`
```
However the order at the end was placed and bot keeps running. 

**Versions:**
Zenbot: 4.0.3
MongoDB: 3.2.11
Node.js: v7.2.1

Full log here:
[zenbot.txt](https://github.com/carlos8f/zenbot/files/1024746/zenbot.txt)

**Comment by esalter** [comment]
I've seen this sometimes too, I think it's a rounding error somewhere when the bot determines how much to purchase with available funds.  It looks like if the price moves "just right" it will be able to execute the order later.

**Comment by carlos8f** [comment]
fixed with 47459d0461810dbacc8b83449cad65bbdde6ed38 , published in v4.0.5

**Comment by vaisov** [comment]
Still happening on Kraken :(
```
Error: Kraken API returned error: Order:Insufficient funds
    at Request._callback (/home/ubuntu/zenbot/node_modules/kraken-api/kraken.js:155:34)
    at Request.self.callback (/home/ubuntu/zenbot/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/ubuntu/zenbot/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/zenbot/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

2017-08-02 16:40:14 - not enough balance for buy, aborting

2017-08-02 16:40:14 - not enough balance, or signal switched, cancel buy
```

**Comment by Skeyelab** [comment]
I'm still having the same issue.

**Comment by jacobgardiner** [comment]
@carlos8f This still occurs for kraken - can you please re-open.
