### ISSUE TITLE
Cannot find module './build/Release/analytics.node'

### ISSUE THREAD

**Issue by leota** [DeviaVir/zenbot#432]
Hi guys, I'm trying to run Zenbot on Ubuntu server 16.04 with node v7.10.1, npm 4.2.0 and python 2.7. After npm install and npm link, if I try to launch any zenbot commands I get this:
```
module.js:472
    throw err;
    ^

Error: Cannot find module './build/Release/analytics.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/leota/zenbot/node_modules/forex.analytics/index.js:1:79)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

```

Has anyone experienced similar issues?

**Comment by jacob-hartmann** [comment]
Same issue here, Debian with Node v8.2.1, npm 5.3.

**Comment by leota** [comment]
Working! Problem was that I run npm install without having "build-essential" installed on my machine, so I installed the package and run npm install again, but without completely wiping previously installed node_modules. So If you're starting with a fresh new install (I'm testing on DigitalOcean droplet Ubuntu 16.04) this has worked for me: 
```
    #install node 
    curl -sL https://deb.nodesource.com/setup_8.x | bash -
    apt-get install nodejs

    #install build-essential
    apt-get install build-essential

    #install python 2
    apt-get install python

    # clone repo and install
    git clone https://github.com/carlos8f/zenbot.git
    cd zenbot
    npm install
    #optional
    npm link
```

**Comment by leota** [comment]
Don't forget to also install mongodb :https://www.digitalocean.com/community/tutorials/how-to-install-mongodb-on-ubuntu-16-04

**Comment by trietdvn** [comment]
Same issue on aws ubuntu 16.04 and aws amazon ami linux.

**Comment by carstenroesner** [comment]
Same issue here on Ubuntu server 16.04 with node v6.11.2, npm 3.10.10 and python 2.7.12:

```
/bitcoin/zenbot# zenbot
module.js:471
    throw err;
    ^

Error: Cannot find module './build/Release/analytics.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/bitcoin/zenbot/node_modules/forex.analytics/index.js:1:79)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```

**Comment by crubb** [comment]
Guys, please upgrade to **nodejs 8**, that should solve the build problem.
Please make sure to `rm -rf node_modules && npm install` to reinstall everything.

Please report back!

**Comment by vitorego** [comment]
I had the same problem and now it works after upgrade do node-js 8 and clear modules folder

thanks

**Comment by crubb** [comment]
A small log from the Discord channel from a user with the same error:

[18:53] derivagral: i'm not sure what you mean? this is from a checked out master on an ubuntu16 digitalocean box
[18:54] derivagral: i upgraded npm from 5.3 to 5.4 and am rerunning npm install atm, perhaps it'll just go away
[18:58] derivagral: looks like it works now, ty for the ping
[19:10] khinklenj: How did you upgrade to 5.4
[19:12] derivagral: v5.3 bugged me to run `npm i -g npm`, after which i removed node_modules & reran `npm install`

**Comment by HeyIamJames** [comment]
Using node 8.9.1 > still cant get it ti work :(

C:\zenbot>npm install
C:\zenbot>npm install
npm ERR! path C:\zenbot\node_modules\forex.analytics
npm ERR! code EISGIT
npm ERR! git C:\zenbot\node_modules\forex.analytics: Appears to be a git
 repo or submodule.
npm ERR! git     C:\zenbot\node_modules\forex.analytics
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

thanks for any insight.

**Comment by rafihm** [comment]
@HeyIamJames 
Remove the node_modules directory and try it.
